# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(194, 194, 194);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(530, 20, 221, 541))
        self.graphicsView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView.setObjectName("graphicsView")
        self.segment_table = QtWidgets.QTableWidget(self.centralwidget)
        self.segment_table.setGeometry(QtCore.QRect(70, 310, 411, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segment_table.sizePolicy().hasHeightForWidth())
        self.segment_table.setSizePolicy(sizePolicy)
        self.segment_table.setMinimumSize(QtCore.QSize(411, 0))
        self.segment_table.setMaximumSize(QtCore.QSize(411, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.segment_table.setFont(font)
        self.segment_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.segment_table.setDragDropOverwriteMode(False)
        self.segment_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.segment_table.setWordWrap(True)
        self.segment_table.setObjectName("segment_table")
        self.segment_table.setColumnCount(3)
        self.segment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.segment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.segment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.segment_table.setHorizontalHeaderItem(2, item)
        self.segment_table.horizontalHeader().setVisible(True)
        self.segment_table.horizontalHeader().setCascadingSectionResizes(False)
        self.segment_table.horizontalHeader().setHighlightSections(False)
        self.segment_table.horizontalHeader().setMinimumSectionSize(45)
        self.segment_table.horizontalHeader().setSortIndicatorShown(False)
        self.segment_table.horizontalHeader().setStretchLastSection(True)
        self.pro_name = QtWidgets.QLabel(self.centralwidget)
        self.pro_name.setGeometry(QtCore.QRect(80, 200, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pro_name.setFont(font)
        self.pro_name.setObjectName("pro_name")
        self.dealloc_reserve = QtWidgets.QPushButton(self.centralwidget)
        self.dealloc_reserve.setGeometry(QtCore.QRect(50, 130, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dealloc_reserve.setFont(font)
        self.dealloc_reserve.setObjectName("dealloc_reserve")
        self.res_start = QtWidgets.QLineEdit(self.centralwidget)
        self.res_start.setGeometry(QtCore.QRect(190, 50, 113, 24))
        self.res_start.setObjectName("res_start")
        self.res_size = QtWidgets.QLineEdit(self.centralwidget)
        self.res_size.setGeometry(QtCore.QRect(190, 90, 113, 24))
        self.res_size.setObjectName("res_size")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 90, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pro_choose = QtWidgets.QComboBox(self.centralwidget)
        self.pro_choose.setGeometry(QtCore.QRect(320, 210, 151, 24))
        self.pro_choose.setObjectName("pro_choose")
        self.alloc = QtWidgets.QPushButton(self.centralwidget)
        self.alloc.setGeometry(QtCore.QRect(70, 520, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.alloc.setFont(font)
        self.alloc.setObjectName("alloc")
        self.alloc_all = QtWidgets.QPushButton(self.centralwidget)
        self.alloc_all.setGeometry(QtCore.QRect(350, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.alloc_all.setFont(font)
        self.alloc_all.setObjectName("alloc_all")
        self.first_fit_radiobtn = QtWidgets.QRadioButton(self.centralwidget)
        self.first_fit_radiobtn.setGeometry(QtCore.QRect(360, 50, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.first_fit_radiobtn.setFont(font)
        self.first_fit_radiobtn.setObjectName("first_fit_radiobtn")
        self.best_fit_radiobtn = QtWidgets.QRadioButton(self.centralwidget)
        self.best_fit_radiobtn.setGeometry(QtCore.QRect(360, 80, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.best_fit_radiobtn.setFont(font)
        self.best_fit_radiobtn.setObjectName("best_fit_radiobtn")
        self.dealloc_current = QtWidgets.QPushButton(self.centralwidget)
        self.dealloc_current.setGeometry(QtCore.QRect(140, 260, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dealloc_current.setFont(font)
        self.dealloc_current.setObjectName("dealloc_current")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pro_choose.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.segment_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Segment Name"))
        item = self.segment_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Base"))
        item = self.segment_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Limit"))
        self.pro_name.setText(_translate("MainWindow", "Process Name:"))
        self.dealloc_reserve.setText(_translate("MainWindow", "Deallocate Reserved Space"))
        self.label.setText(_translate("MainWindow", "Starting Address"))
        self.label_2.setText(_translate("MainWindow", "Size"))
        self.alloc.setText(_translate("MainWindow", "Allocate by Segment"))
        self.alloc_all.setText(_translate("MainWindow", "Allocate All"))
        self.first_fit_radiobtn.setText(_translate("MainWindow", "First Fit"))
        self.best_fit_radiobtn.setText(_translate("MainWindow", "Best Fit"))
        self.dealloc_current.setText(_translate("MainWindow", "Deallocate Current Process"))
